<?php

declare(strict_types=1);

use Jhernandes\AciRedShield\Domain\TransactionId;
use PHPUnit\Framework\TestCase;

class TransactionIdTest extends TestCase
{
    public function testCanBeCreatedFromValidString(): void
    {
        $this->assertInstanceOf(TransactionId::class, TransactionId::fromString('123456'));
    }

    public function testCannotBeCreatedFromEmptyString(): void
    {
        $this->expectException(\DomainException::class);

        TransactionId::fromString('');
    }

    public function testCannotBeCreatedFromStringGreaterThan255Characters(): void
    {
        $this->expectException(\DomainException::class);

        TransactionId::fromString('Idamettemporexercitationlaborisnullaipsumlaborumetnisiquisdolaboris.Noneuconsequatullamcomagnamollitofficianullaetexcepteurduisdoelit.Nonnoncillumlaborumidetindoincididuntesse.Sintanimadipisicingvelitpariatur.UtLoremcillumconsequat.Duisestipsumestirureetcommodoreprehenderitidofficia.Velitdoloresunteiusmodmollitidnulladolore.Officianullaquimagnafugiatinnulla.AdipisicingfugiatelitametofficiaLoremanimfugiatofficia.AmetestsuntsunteaidoccaecatlaboreminimlaborumeiusmodexcepteurvelitLorem.Deseruntcupidatatesseexcepteurlaboreullamcoquiipsumpariaturlaborisdoloreadipisicingculpaduismagna.Auteametnisiconsecteturetametullamcominim.Proidentincididuntquisinutadipisicingaliquipnisi.Quicillumametlaborispariaturconsecteturcupidatatofficiaculpaconsecteturcillumelit.Estcillumdolorvoluptatesitnonesseanim.Proidentveniamsintipsumipsumsunt.Enimfugiateuminimfugiatdeseruntvoluptateesseadipisicingoccaecatincididuntincididuntetnostrudaliquaveniam.Enimelitexercitationanimdolorenondoqui.Enimsiteaproidentduisnostrudculpaelitreprehenderit.UllamcoconsecteturofficiadoquiLoremduisnostrudnisiametminimirureadipisicingoccaecatea.Exercitationvoluptatepariaturvoluptateanimoccaecateiusmodadadipisicingadeunulla.Laborissintduisreprehenderitanimipsumdoestexercitationoccaecatmagna.Exdeseruntexercitationenimaute.Velitnullanisiesseduiscupidatatduis.Temporlaborelaborisanimnullaproidentdeseruntmollitincididunteiusmodexeiusmoddonisiconsequat.AliquaconsequatLoremullamconostrudadipisicing.Eteiusmodmagnatemporirurecillumsint.Suntlaborumsintmagnaexcepteurautesint.EtconsecteturexdeseruntnisidolorametipsumLoremmollitadadipisicing.Exercitationlaborumullamcoquiutestexirureeu.Temporreprehenderitsitfugiatenimnostrudofficiamagnacillumofficiaoccaecatquiadipisicingminimdo.Animdoloreenimdeseruntlaborum.Enimeanullaexercitationexercitationmagnaetanimoccaecat.Laborumsitiruresuntexercitationeamagnaconsectetur.Eairureofficiaproidentexcepteurduisirurenonlaborum.SitnullaconsequatanimelitculpaLoremvoluptatedeseruntoccaecat.Iruresitcillumullamcovelit.Cillumettemporquisametexercitationeaquinisipariaturaliquaessequisautemagnaest.Animquisculpaeuveniamminimtemporidnullairureexcepteurexexutqui.Amettemporipsumduiseudolorveniamlaborisdolaborumnisi.Exercitationullamcofugiatofficiaconsecteturconsequatanimextemporvelitanim.Reprehenderitsitenimexeiusmod.Deserunteuminimmollit.Consequatproidentsintfugiatlaborisin.Aliquaproidentlaborisconsequatculpasinteiusmodcillumminimreprehenderitoccaecatnisiminimpariaturpariatur.Cupidatatsuntexercitationconsequatmagnaofficiaesseexconsequatsitculpapariaturlaboris.Officiaincididuntipsumsitmagnaculpacillum.Autenostrudreprehenderitvelit.AutelaborisLoremid.Irurenisiidquiirureutexauteeusit.Laborepariaturdocommodocupidatatoccaecatutessenisiamet.Deseruntnisieaexercitationmagnacillumessequis.Eavelitsuntaliquatemporincididuntdolornon.Temporametreprehenderitadconsecteturnisiauteelitcupidatatelitauteaute.Deseruntauteexcepteurdeseruntanimaliquip.Velitlaboretemporesseconsequat.Laboretemporsitfugiatofficiaanimconsecteturmollit.AliquipadipisicingeaadnonirureelittemporestLoremvoluptateoccaecatveniamut.Elitestdeseruntullamcoenimoccaecateuirure.Proidentaddeseruntaliqua');
    }

    public function testCannotBeCreatedFromInvalidString(): void
    {
        $this->expectException(\DomainException::class);

        TransactionId::fromString(']~23324;]~1;]~1]2~51;~21]51~25');
    }
}
