<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Jhernandes\AciRedShield\Domain\Customer\CustomerId;

class CustomerIdTest extends TestCase
{
    public function testCanBeCreatedFromString(): void
    {
        $this->assertInstanceOf(CustomerId::class, CustomerId::fromString('ABCD123456789'));
    }

    public function testCannotBeCreatedFromInvalidString(): void
    {
        $this->expectException(\DomainException::class);

        CustomerId::fromString('!@#$%ˆ*ˆ&*(&');
    }

    public function testCannotBeCreatedFromEmptyString(): void
    {
        $this->expectException(\DomainException::class);

        CustomerId::fromString('');
    }

    public function testCannotBeCreatedFromMoreThan255Characters(): void
    {
        $text = "Idamettemporexercitationlaborisnullaipsumlaborumetnisiquisdolaboris.Noneuconsequatullamcomagnamollitofficianullaetexcepteurduisdoelit.Nonnoncillumlaborumidetindoincididuntesse.Sintanimadipisicingvelitpariatur.UtLoremcillumconsequat.Duisestipsumestirureetcommodoreprehenderitidofficia.Velitdoloresunteiusmodmollitidnulladolore.Officianullaquimagnafugiatinnulla.AdipisicingfugiatelitametofficiaLoremanimfugiatofficia.AmetestsuntsunteaidoccaecatlaboreminimlaborumeiusmodexcepteurvelitLorem.Deseruntcupidatatesseexcepteurlaboreullamcoquiipsumpariaturlaborisdoloreadipisicingculpaduismagna.Auteametnisiconsecteturetametullamcominim.Proidentincididuntquisinutadipisicingaliquipnisi.Quicillumametlaborispariaturconsecteturcupidatatofficiaculpaconsecteturcillumelit.Estcillumdolorvoluptatesitnonesseanim.Proidentveniamsintipsumipsumsunt.Enimfugiateuminimfugiatdeseruntvoluptateesseadipisicingoccaecatincididuntincididuntetnostrudaliquaveniam.Enimelitexercitationanimdolorenondoqui.Enimsiteaproidentduisnostrudculpaelitreprehenderit.UllamcoconsecteturofficiadoquiLoremduisnostrudnisiametminimirureadipisicingoccaecatea.Exercitationvoluptatepariaturvoluptateanimoccaecateiusmodadadipisicingadeunulla.Laborissintduisreprehenderitanimipsumdoestexercitationoccaecatmagna.Exdeseruntexercitationenimaute.Velitnullanisiesseduiscupidatatduis.Temporlaborelaborisanimnullaproidentdeseruntmollitincididunteiusmodexeiusmoddonisiconsequat.AliquaconsequatLoremullamconostrudadipisicing.Eteiusmodmagnatemporirurecillumsint.Suntlaborumsintmagnaexcepteurautesint.EtconsecteturexdeseruntnisidolorametipsumLoremmollitadadipisicing.Exercitationlaborumullamcoquiutestexirureeu.Temporreprehenderitsitfugiatenimnostrudofficiamagnacillumofficiaoccaecatquiadipisicingminimdo.Animdoloreenimdeseruntlaborum.Enimeanullaexercitationexercitationmagnaetanimoccaecat.Laborumsitiruresuntexercitationeamagnaconsectetur.Eairureofficiaproidentexcepteurduisirurenonlaborum.SitnullaconsequatanimelitculpaLoremvoluptatedeseruntoccaecat.Iruresitcillumullamcovelit.Cillumettemporquisametexercitationeaquinisipariaturaliquaessequisautemagnaest.Animquisculpaeuveniamminimtemporidnullairureexcepteurexexutqui.Amettemporipsumduiseudolorveniamlaborisdolaborumnisi.Exercitationullamcofugiatofficiaconsecteturconsequatanimextemporvelitanim.Reprehenderitsitenimexeiusmod.Deserunteuminimmollit.Consequatproidentsintfugiatlaborisin.Aliquaproidentlaborisconsequatculpasinteiusmodcillumminimreprehenderitoccaecatnisiminimpariaturpariatur.Cupidatatsuntexercitationconsequatmagnaofficiaesseexconsequatsitculpapariaturlaboris.Officiaincididuntipsumsitmagnaculpacillum.Autenostrudreprehenderitvelit.AutelaborisLoremid.Irurenisiidquiirureutexauteeusit.Laborepariaturdocommodocupidatatoccaecatutessenisiamet.Deseruntnisieaexercitationmagnacillumessequis.Eavelitsuntaliquatemporincididuntdolornon.Temporametreprehenderitadconsecteturnisiauteelitcupidatatelitauteaute.Deseruntauteexcepteurdeseruntanimaliquip.Velitlaboretemporesseconsequat.Laboretemporsitfugiatofficiaanimconsecteturmollit.AliquipadipisicingeaadnonirureelittemporestLoremvoluptateoccaecatveniamut.Elitestdeseruntullamcoenimoccaecateuirure.Proidentaddeseruntaliqua";

        $this->assertGreaterThan(255, strlen($text));

        $this->expectException(\DomainException::class);
        CustomerId::fromString($text);
    }
}
